project:
  type: website

website:
  page-navigation: true
  title: "STA 210 - Spring 2022"
  sidebar:
    background: "#D9E3E4"
    logo: "images/iest422_logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta210-s22
        text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - text: Overview
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
freeze: auto

editor: visual

