---
title: "Diagramas de control para atributos"
subtitle: "IEST 422 - 2022/02"
author: "Eloy Alvarado Narváez"
institute: "Universidad de Valparaíso"
date: 10/11/22
format: 
  revealjs:
    theme: slides.scss
    touch: true
    slide-level: 2
incremental: true
slide-number: true
lang: es
highlight-style: github
width: 1600
height: 900
logo: images/logo_uv.png
transition: fade
footer: "IEST 422 - Semana 10"
execute:
  freeze: auto
---

# Diagramas de control para atributos

Muchas características de la calidad no pueden ser convenientemente representadas numéricamente, en aquellos casos, usualmente clasificamos cada *item* como conforme o no, con respecto a estándares deseados. También podemos llamarlos defectuoso o no defectuoso, pero la primera terminología es la más utilizada.

Este tipo de características de la calidad le llamamos **atributos**

## Diagramas de control para proporción no conforme

La fracción no conforme está definido como la relación del número de *items* no conformes en una población y el número total de artículos en esa población. Los artículos pueden tener **muchas** características de interés que son examinadas simultáneamente por un inspector. Si un artículo no satisface el estándar en una o más de aquellas características, se clasifica aquel producto como **no conforme**.

Si bien nos concentraremos principalmente en la proporción de productos no conformes, el análisis es análogo si deseamos enfocarnos en la proporción de productos conformes.

## Diagramas de control para fracción no conforme: continuación

El principio estadístico que subyace los diagramas de control para fracción no conforme es la **distribución binomial**.

La proporción muestral de no conformes se define como:

$$\hat{p}=\dfrac{D}{n}$$

Donde $D$ es el número de unidades conformes en la muestra y $n$ es el tamaño de muestra. Por cursos anteriores, sabemos que la distribución de la variable aleatoria $\hat{p}$ es binomial, y además, la media y varianza de $\hat{p}$ son:

$$\mu_{\hat{p}}=p \qquad \sigma_{\hat{p}}^{2}=\dfrac{p(1-p)}{n},$$

respectivamente. Este tipo de herramienta de control de calidad se les llama diagramas para $p$.

## Desarrollo y operación del diagrama de control

Si $w$ es un estadístico que mide una característica de la calidad, y si la media y varianza están dados por: $\mu_{w}$ y $\sigma_{w}^{2}$, entonces el modelo general de un diagrama de control de Shewhart es:

\begin{align*}
UCL &= \mu_{w}+ L \sigma_{w} \\
CL &= \mu_{w} \\
LCL &= \mu_{w} - L\sigma_{w}
\end{align*}

donde $L$ es la distancia de los límites de control desde la línea central, en múltiplos de la desviación estándar de $w$. Usualmente escogemos $L=3$.

## Desarrollo y operación del diagrama de control: continuación

Supongamos que la verdadera proporción de no conformidad $p$ en el proceso de producción es conocida o es un valor estándar específico, entonces las ecuaciones anteriores serán:

\begin{align*}
UCL&= p + 3 \sqrt{\dfrac{p(1-p)}{n}}\\
CL &= p \\
LCL &= p - 3\sqrt{\dfrac{p(1-p)}{n}}
\end{align*}

Dependiendo de los valores de $p$ y $n$, a veces el límite de control inferior será negativo, en aquellos casos decimos que $LCL=0$ y asumimos que el diagrama de control sólo tiene un límite de control superior.


## Desarrollo y operación del diagrama de control: continuación

Cuando la proporción de no conformidad del proceso $p$ no es conocida, debemos estimarla desde los datos a disposición. El procedimiento usual consiste en seleccionar $m$ muestral preliminares, cada una de tamaño $n$. Como regla general $m$ debe ser al menos 20 o 25. Luego, si hay $D_i$ artículos no conformes en la muestra $i$, calculamos la fracción de no conformidad en la muestra $i-$ésima como:

$$\hat{p}_i=\dfrac{D_i}{n} \quad i=1,2,\dots,m$$

y el promedio de estas muestras individuales es:

$$\overline{p}=\dfrac{\sum_{i=1}^{m}D_i}{mn}=\dfrac{\sum_{i=1}^{m}\hat{p}_i}{m}$$
El estadístico $\overline{p}$ estima la fracción desconocida de no conformidad $p$.

## Desarrollo y operación del diagrama de control: continuación

La línea central y los límites del diagrama de control para la proporción de no confirmidad se calculan como:


\begin{align*}
UCL&= \overline{p} + 3 \sqrt{\dfrac{\overline{p}(1-\overline{p})}{n}}\\
CL &= \overline{p} \\
LCL &=  \overline{p} - 3 \sqrt{\dfrac{\overline{p}(1-\overline{p})}{n}}
\end{align*}

Los límites de control definidos anteriormente deben ser consideramos como **límites de control preliminares**.

**Revisar Ejemplo 7.1. Introduction to statistical quality control. Montgomery, Douglas C. 7th edition.**

## Diseño de un diagrama de control para p

Los diagramas de control para $p$ o diagramas de control para la proporción de no conformidad tienen 3 parámetros que deben ser especificados: 

- Tamaño de muestra
- Frecuencia de muestreo
- Ancho de los límites de control

. . .

Idealmente, debemos seguir algunas recomendaciones generales para seleccionar estos parámetros.

## Diseño de un diagrama de control para p: continuación

Es relativamente común basar el diagrama de control para $p$ en el $100\%$ de inspecciones de **todos** las salidas del proceso a lo largo de un periodo de tiempo conveniente, por ejemplo, a lo largo de un día. En este caso, el tamaño de muestra y la frecuencia de muestreo están interrelacionadas.

En general, debemos seleccionar una frecuencia de muestreo apropiada para la tasa de producción, y esto fija el tamaño de muestra.

Los subgrupos racionales pueden tomar un rol fundamental en la determinación de la frecuencia de muestreo.

## Diseño de un diagrama de control para p: continuación

Si seleccionamos una muestra de las salidas del proceso, debemos escoger un tamaño de muestra $n$. Si $p$ es pequeño, debemos escoger $n$ lo suficientemente grande tal que tengamos una gran probabilidad de encontrar al menos un artículo no conforme en la muestra. Sino, podemos caer en el caso en donde el proceso se considerará fuera de control tras encontrar solo un artículo no conforme. Por ejemplo, si $p=0.01$ y $n=8$, se tiene que el límite superior de control es:

$$UCL=p+3\sqrt{\dfrac{p(1-p)}{n}}=0.01+3\sqrt{\dfrac{0.01*0.99}{8}}=0.1155$$

Si hay un artículo no conforme en la muestra, entonces $\hat{p}=0.125$, y concluiríamos que el proceso está fuera de control.

## Diseño de un diagrama de control para p: continuación

Para evitar este problemas, podemos escoger un tamaño de muestra $n$ de tal manera que la probabilidad de encontrar al menos una unidad no conforme por muestra sea de al menos $\gamma$. Por ejemplo, si suponemos que $p=0.01$ y queremos que la probabilidad de que al menos una unidad no conforme en la muestra sea de 0.95. Si denotamos $D$ como el número de artículo no conformes en la muestra, entonces queremos encontrar $n$ tal que $\mathbb{P}(D\geq 1)\geq 0.95 \Leftrightarrow \mathbb{P}(D=0)=0.05$. Así,

$$ \mathbb{P}(D=0)= \dfrac{n!}{0!(n-0)!}0.01^0(1-0.01)^{n-0} \Leftrightarrow 0.05 = 0.99^n$$

Resolviendo esta ecuación nos da un tamaño de muestra $n=298$. Alternativamente, podemos calcular el tamaño de muestra usando la aproximación de Poisson a la distribución binomial.

## Diseño de un diagrama de control para p: continuación

Ducan ha sugerido que el tamaño de muestra debe ser lo suficientemente grande tal que tengamos un $50\%$ de probabilidad de detectar un cambio de una cantidad específica en el proceso. Por ejemplo, supongamos que $p=0.01$, y queremos que la probabilidad de detectar un cambio a $p=0.05$ sea de 0.5. Asumiendo que la aproximación normal a la distribución binomial aplica, debemos escoger $n$ tal que el límite superior de control coincida con la fracción de no conformidad en el estado de no-control.

Si $\delta$ es la magnitud del cambio en el proceso, entonces $n$ debe satisfacer:

$$\delta=L\sqrt{\dfrac{p(1-p)}{n}}$$

Así,

$$n=\left(\dfrac{L}{\delta}\right)^2 p(1-p)$$


## Diseño de un diagrama de control para p: continuación

En nuestro ejemplo, $p=0.01, \delta=0.05-0.01=0.04$, y si límites $3-$sigma son utilizados, entonces se tiene:

$$n=\left(\dfrac{3}{0.04}\right)^2 0.01 * 0.99 = 56$$

Si los valores de control de la proporción de no conformidad son pequeños, es recomendable escoger $n$ lo suficientemente grande tal que el diagrama de control tenga un límite inferior positivo. En nuestro ejemplo:

$$n> \dfrac{(1-p)}{p}L^2$$
Por ejemplo, si $p=0.05$ y se usan límites $3-$sigma, el tamaño de muestra necesario será:

$$n > \dfrac{0.95}{0.05} 3^2=171$$

## Diagramas de control np

También es posible basar el diagrama de control en el número de artículo no conformes en vez de la proporción. A este de herramienta se la llama **diagrama de control $np$** y sus límites serán

\begin{align*}
UCL&= np + 3 \sqrt{np(1-p)}\\
CL &= np \\
LCL &= np - 3\sqrt{np(1-p)}
\end{align*}

**Revisar Sección 7.2.2: Variable Sample Size**

# Diagramas de control para defectos

Un artículo no conforme es aquel que no satisface una o más de las especificaciones para aquel producto. Cada punto específico en el que no se cumple una especificación da como resultado un **defecto** o **no conformidad**. Por consecuencia, un artículo no conforme tendrá al menos un defecto. Sin embargo, dependiendo de su naturaleza y severidad, es posible que una unidad contenga muchos defecto y no sea clasificado como no conforme.

Por ejemplo, supongamos que se manufacturan computadores. Cada unidad podría tener uno o más pequeños defectos, y si estos no afectan gravemente la funcionalidad del computador, podría ser clasificado como conforme. Sin embargo, si el computador tiene muchos defectos, debiese ser clasificado como **no conforme**.

## Diagramas de control para defectos: continuación

Es posible desarrollar diagramas de control para el **número total de no conformidades o defectos** en una unidad o para el **número promedio de no conformidades o defectos por unidad**. Usualmente, este tipo de diagramas de control asume que la ocurrencia de no conformidades en muestras de tamaño constante se puede modelar mediante una distribución Poisson.

. . .

**¿Qué supuesto deberemos hacer para modelar mediante una distribución de Poisson?**

. . .

Requeriremos que el número de oportunidades o potenciales lugares de no conformidad sea infinito y que la probabilidad de ocurrencia de una no conformidad en cualquier área sea pequeña y constante. Además, la **unidad de inspección** debe ser la misma para cada muestra, esto es, cada unidad de inspección debe ser siempre representar un **área de oportunidad** idéntica para la ocurrencia de no conformidades.

En la práctica, estas condiciones no se verán satisfechas exactamente.

## Procedimientos con tamaño de muestra constante

Consideremos la ocurrencia de no conformidades en una unidad de inspección del producto. En la mayoría de los casos, la unidad inspeccionada será un solo producto, sin embargo esto puede diferir dependiendo de la naturaleza del proceso.

Supongamos que el número de defecto o no conformidades se distribuye Poisson, así:

$$p(x)=\dfrac{e^{-c}c^x}{x!}\qquad x=0,1,2,\dots$$
donde $x$ es el número de no conformidades y $c>0$ es el parámetro de la distribución Poisson.


## Procedimientos con tamaño de muestra constante: continuación

Por lo anterior, una **diagrama de control para defectos o no conformidades** (o diagrama para $c$ con límites $3-$sigma estará dado por:

\begin{align*}
UCL &= c + 3\sqrt{c}\\
CL &= c \\
LCL &= c - 3\sqrt{c}
\end{align*}

Si tenemos un valor estándar para $c$. Sino, tendremos que estimarlo como el número promedio de no conformidades en una muestra grande, digamos $\overline{c}$. Así,

\begin{align*}
UCL &= \overline{c} + 3\sqrt{\overline{c}}\\
CL &= \overline{c} \\
LCL &= \overline{c} - 3\sqrt{\overline{c}}
\end{align*}

## Análisis del no conformidades

Datos de defectos o no conformidades siempre serán más informativos que los diagramas de proporción no conformes, debido a que usualmente habrán diferentes tipos de no conformidades o defectos. Al analizar los defectos por tipo, tendremos una mayor visión sobre las causas asignables que provocaron el defecto. Esto puede ser particularmente útil al desarrollar los **OCAP** (*out-of-control-action plans*) que deben acompañar a un diagrama de control.

## Elección del tamaño de muestra:

En lo anterior utilizamos un tamaño de muestra unitario. Sin embargo, en la práctica desearemos  inspeccionar la mayor cantidad de unidades posible. Este tamaño muestral debe ser escogido de acuerdo con consideraciones estadísticas como:

- El tamaño de muestra sea lo suficientemente grande para asegurar un límite inferior de control positivo
- Obtener probabilidades particulares para la detección de un cambio

. . .

Alternativamente, factores económicos pueden tener un rol fundamental en la elección del tamaño de muestra.

## Diagrama de control para u{.small}

Si deseamos construir un diagrama de control para el **número promedio de no conformidades por unidad de inspección**, definimos el número promedio de no conformidades por unidad de inspección como:

$$u=\dfrac{x}{n}$$

en donde, $x$ es el número total de no conformidades en una muestra de $n$ unidades de inspección. Además, notamos que $x$ es una variable aleatoria Poisson, en consecuencia se tiene:

\begin{align*}
UCL &= \overline{u} + 3\sqrt{\dfrac{\overline{u}}{n}}\\
CL &= \overline{u} \\
LCL &= \overline{u} - 3\sqrt{\dfrac{\overline{u}}{n}}
\end{align*}

donde $\overline{u}$ representa el número promedio observado de no conformidades por unidad en un conjunto de datos.

# Sistemas de demérito

Con productos de mayor complejidad como autos o computadores, usualmente nos encontraremos diferentes tipos de defectos o no conformidades. **No todos los tipos de defectos son igualmente importantes**.

Una unidad que tenga un defecto severo será probablemente clasificado como no conforme, pero una unidad que tenga varios defectos menores no necesariamente se clasificará de igual manera.

En estas situaciones, necesitaremos un método para clasificar los defectos dependiendo de la gravedad y para ponderar los distintos tipos de no conformidades de manera razonable.

## Sistemas de demérito: continuación

**Los sistemás de demérito para datos de atributo** pueden ser útiles en estos casos. Un posible esquema de demérito es el siguiente:

- **Defectos Clase A, muy grave**: La unidad es completamente inapropiada para el servicio o fallará en el servicio de tal manera que no se puede corregir fácilmente  o causará lesiones personales o daños a la propiedad.

- **Defectos Clase B, grave**: Es posible que la unidad sufra una falla de operación de Clase A, cause problemas de operación algo menos serios o tendrá una vida útil reducida o un mayor costo de mantenimiento.

- **Defectos Clase C, moderadamente grave**: Es posible que la unidad falle en servicio, cause problemas que sean menos serios que una falla operativa, posiblemente tenga una vida útil reducida o aumenten los costos de mantenimiento, tenga un defecto importante en el acabado, la apariencia o la calidad del trabajo.

- **Defectos Clase D, menores**: La unidad no fallará en el servicio, pero tiene defectos menores en el acabado, apariencia o calidad del trabajo.

## Sistemas de demérito: continuación

Sean $c_{iA}, c_{iB}, c_{iC}$ y $c_{iD}$ el número de defectos Clases A, B, C y D, respectivamente, en la unidad de inspección $i-$ésima. Asumiremos que cada clase de defectos es independiente, y la ocurrencia de defectos en cada clase es correctamente modelada mediante una distribución de Poisson. Así, definimos el **número de deméritos** en la  unidad de inspección como:

$$d_i=100 c_{iA}+ 50 c_{iB} + 10  c_{iC} + c_{iD}$$

En donde los pesos asociados son los comúnmente usados en la práctica. Sin embargo, estos pueden ser cambiados dependiendo de la naturaleza del proceso.

## Sistemas de demérito: continuación{.small}

Supongamos que una muestra de $n$ unidades de inspección es usada. Entonces el número de deméritos por unidad está dado por:

$$y_i=\dfrac{D}{n}$$

donde $D=\sum_{i=1}^{n}d_i$ es el número total de deméritos en todas las $n$ unidades de inspección. Debido a que $u_i$ es una combinación lineal de V.A. Poisson independientes, el estadístico $u_i$ puede ser graficado en un diagrama de control como:


\begin{align*}
UCL &= \overline{u} + 3\hat{\sigma}_u\\
CL &= \overline{u} \\
LCL &= \overline{u} - 3\hat{\sigma}_u
\end{align*}

donde,

$$\overline{u}=100 \overline{u}_A +  50 \overline{u}_B + 10 \overline{u}_C + \overline{u}_D$$

y,

$$\hat{\sigma}_u=\left[ \dfrac{100^2 \overline{u}_A +  50^2 \overline{u}_B + 10^2 \overline{u}_C + \overline{u}_D}{n}\right]^{1/2}$$
# ¿Diagramas de control para atributos o variables?

- ¿Cuáles son las ventajas de los diagramas de control para atributos?

- ¿Cuáles son las ventajas de los diagramas de control para variables?

. . .

**Tarea: Leer Sección 7.5: Guideliens for implementing Control Charts. Introduction to statistical quality control. Montgomery, Douglas C. 7th edition.**


# ¿Qué veremos la próxima semana?

- Capacidad del proceso (en detalle)

# ¿Qué deben preparar para la próxima semana?

- Estudiar Capítulo 8. Introduction to statistical quality control. Montgomery, Douglas C. 7th edition.