---
title: "Calendario"
---

|          Semana          | Fecha |              Preparaci贸n               |              Presentaci贸n               |              Material adicional               | Prueba | Trabajo Final |
|:------------------------:|:-----:|:--------------------------------------:|:---------------------------------------:|:---------------------------------------------:|:------:|:-------------:|
|  [1](/pages/week1.html)  | 25/08 | [](../pages/week1.html#preparaci贸n)  | [ワ](../pages/week1.html#presentaci贸n)  | [](../pages/week1.html#material-adicional)  |        |               |
|  [2](/pages/week2.html)  | 01/09 | [](../pages/week2.html#preparaci贸n)  | [ワ](../pages/week2.html#presentaci贸n)  | [](../pages/week2.html#material-adicional)  |        |               |
|  [3](/pages/week3.html)  | 08/09 | [](../pages/week3.html#preparaci贸n)  | [ワ](../pages/week3.html#presentaci贸n)  | [](../pages/week3.html#material-adicional)  |        |               |
|  [4](/pages/week4.html)  | 15/09 | [](../pages/week4.html#preparaci贸n)  | [ワ](../pages/week4.html#presentaci贸n)  | [](../pages/week4.html#material-adicional)  |        |               |
|  [5](/pages/week5.html)  | 29/09 | [](../pages/week5.html#preparaci贸n)  | [ワ](../pages/week5.html#presentaci贸n)  | [](../pages/week5.html#material-adicional)  |        |               |
|  [6](/pages/week6.html)  | 06/10 | [](../pages/week6.html#preparaci贸n)  | [ワ](../pages/week6.html#presentaci贸n)  | [](../pages/week6.html#material-adicional)  |        |               |
|  [7](/pages/week7.html)  | 13/10 | [](../pages/week7.html#preparaci贸n)  | [ワ](../pages/week7.html#presentaci贸n)  | [](../pages/week7.html#material-adicional)  |        |               |
|  [8](/pages/week8.html)  | 20/10 | [](../pages/week8.html#preparaci贸n)  | [ワ](../pages/week8.html#presentaci贸n)  | [](../pages/week9.html#material-adicional)  |        |               |
|  [9](/pages/week9.html)  | 27/10 | [](../pages/week9.html#preparaci贸n)  | [ワ](../pages/week9.html#presentaci贸n)  | [](../pages/week9.html#material-adicional)  |      |               |
| [10](/pages/week10.html) | 10/11 | [](../pages/week10.html#preparaci贸n) | [ワ](../pages/week10.html#presentaci贸n) | [](../pages/week10.html#material-adicional) |        |               |
| [11](/pages/week11.html) | 17/11 | [](../pages/week11.html#preparaci贸n) | [ワ](../pages/week11.html#presentaci贸n) | [](../pages/week11.html#material-adicional) |        |               |
| [12](/pages/week12.html) | 24/11 | [](../pages/week12.html#preparaci贸n) | [ワ](../pages/week12.html#presentaci贸n) | [](../pages/week12.html#material-adicional) |        |               |
| [13](/pages/week13.html) | 01/12 | [](../pages/week13.html#preparaci贸n) | [ワ](../pages/week13.html#presentaci贸n) | [](../pages/week13.html#material-adicional) |      |             |
| [14](/pages/week14.html) | 08/12 | [](../pages/week14.html#preparaci贸n) | [ワ](../pages/week14.html#presentaci贸n) | [](../pages/week14.html#material-adicional) |        |               |
| [15](/pages/week15.html) | 15/12 | [](../pages/week15.html#preparaci贸n) | [ワ](../pages/week15.html#presentaci贸n) | [](../pages/week15.html#material-adicional) |        |             |
| [16](/pages/week16.html) | 22/12 | [](../pages/week16.html#preparaci贸n) | [ワ](../pages/week16.html#presentaci贸n) | [](../pages/week16.html#material-adicional) |        |             |
